### ISSUE TITLE
Add support for enabling/disabling Anonymous repository access

### ISSUE THREAD

**Issue by InfoSec812** [InfoSec812/nexus-kubernetes-openshift#16]
My first thought on this is a single ConfigMap which has keys for each repository to indicate if it should be accessible anonymously or not. For example:

```
apiVersion: v1
data:
  maven-central: 'true'
  myNugetRepo: 'true'
  myDockerGroup: 'false'
kind: ConfigMap
metadata:
  name: my-blobstore
  namespace: labs-ci-cd
  labels:
    nexus-type: anonymous
```

The plugin would read and parse the data, and set anonymous access appropriately. IF a repository is not listed, the plugin will not modify access for that repository.

Another possibility is allowing for a `default` which would set all repositories to either allow or disallow anonymous access globally.

**Comment by InfoSec812** [comment]
Actually, I am reconsidering this approach for something which will be more granular and flexible. There would be a new ConfigMap labelled type which defines `roles` and in those roles we would assign privileges. For example:

```
apiVersion: v1
data:
  privileges: 'nx-repository-admin-*-*-read,''nx-repository-admin-*-*-browse,'nx-repository-admin-*-*-add''
kind: ConfigMap
metadata:
  name: nx-anonymous
  labels:
    nexus-type: role
```

This would create/update the specified role. We would also need to consider how we assign `nx-anonymous` for various repositories as well.
